#pragma once

#include "data_structs.h"


enum ReturnCodes {
    SUCCESS = 0,
    NO_INPUT_FILES,
    FILE_NOT_EXIST,
    LINE_TOO_LONG,
    LABEL_ALREADY_EXIST,
    INVALID_LABEL,
    MEMORY_ALLOCATION_FAILED,
    INVALID_OPCODE,
    WRONG_AMOUNT_OF_OPERANDS,
    INVALID_SRC_OPERAND_ADDRESSING_MODE,
    INVALID_DST_OPERAND_ADDRESSING_MODE,
    ENTRY_LABEL_DOESNT_EXIST,
    LABEL_DOES_NOT_EXIST,
    INVALID_JUMP_TO_EXTERNAL_ADDRESS
};

extern const char* OPCODE_STRINGS[16];

extern const OpcodeRule OPCODE_TABLE[16];

extern const int OPCODE_TABLE_SIZE;
